web:
  host: 127.0.0.1
  userport: 8080
  adminport: 8081

mysql:
  user: root
  password: "006620"
  host: 127.0.0.1
  port: 3306
  db: mygoim
  MaxIdleConns: 10
  MaxOpenConns: 300

reids:
  addr: 127.0.0.1:6379
  password: ""
  db: 6
  PoolSize: 10

JWT:
  secret: "Ononoki"
  ttl: 6000

WS:
  ReadBufferSize: 1024
  WriteBufferSize: 1024

rabbitMQ:
  host: 127.0.0.1
  port: 5672
  user: guest
  password: guest

maxWorker: 200